name: arcore_flutter_plugin_example
description: Demonstrates how to use the arcore_flutter_plugin plugin.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  permission_handler: ^9.2.0
  path_provider: ^2.0.9
  http: ^0.13.4
  firebase_ml_vision: ^0.9.7
  image_picker:
  clipboard: ^0.1.2+8
  image: ^3.0.2
  flutter_colorpicker: ^1.0.3
  barcode_scan2: ^4.2.0
  flutter_native_image: ^0.0.6
  google_fonts: ^2.3.2
  flutter_svg: ^1.0.3
  curved_navigation_bar: ^0.3.2
  dio: ^1.0.13
  font_awesome_flutter: ^8.2.0
  rxdart: ^0.27.3
  sqflite:
  path:
  barcode_widget: ^2.0.2
  flutter_barcode_scanner: ^2.0.0
  dropdown_search: ^3.0.1
  edge_detection: ^1.0.9

  # downloads_path_provider_28: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  arcore_flutter_plugin:
    path: ../
  flutter_native_splash: ^1.2.3

flutter_native_splash:
  # background_image: "assets/images/launch_image.jpg"
  color: "#0F52BA"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  image: assets/images/ARLogomdpi.png
  fullscreen: true
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Updock
      fonts:
        - asset: assets/fonts/Updock-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/hishem.png
    - assets/qrcode.png
    - assets/user.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
